rawfiles:
  Allstarfull: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/AllstarFull.csv
  Appearances: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Appearances.csv
  AwardsManagers: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/AwardsManagers.csv
  AwardsPlayers: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/AwardsPlayers.csv
  AwardsShareManagers: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/AwardsShareManagers.csv
  AwardsSharePlayers: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/AwardsSharePlayers.csv
  Batting: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Batting.csv
  BattingPost: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/BattingPost.csv
  CollegePlaying: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/CollegePlaying.csv
  Fielding: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Fielding.csv
  FieldingOF: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/FieldingOF.csv
  FieldingOFsplit: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/FieldingOFsplit.csv
  FieldingPost: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/FieldingPost.csv
  HallOfFame: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/HallOfFame.csv
  HomeGames: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/HomeGames.csv
  Managers: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Managers.csv
  ManagersHalf: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/ManagersHalf.csv
  Parks: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Parks.csv
  People: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/People.csv
  Pitching: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Pitching.csv
  PitchingPost: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/PitchingPost.csv
  Salaries: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Salaries.csv
  Schools: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Schools.csv
  SeriesPost: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/SeriesPost.csv
  Teams: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/Teams.csv
  TeamsFranchises: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/TeamsFranchises.csv
  TeamsHalf: https://raw.githubusercontent.com/chadwickbureau/baseballdatabank/master/core/TeamsHalf.csv
